# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_spectrum_latency_swig', [dirname(__file__)])
        except ImportError:
            import _spectrum_latency_swig
            return _spectrum_latency_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_spectrum_latency_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _spectrum_latency_swig = swig_import_helper()
    del swig_import_helper
else:
    import _spectrum_latency_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def high_res_timer_now():
  """high_res_timer_now() -> gr::high_res_timer_type"""
  return _spectrum_latency_swig.high_res_timer_now()

def high_res_timer_now_perfmon():
  """high_res_timer_now_perfmon() -> gr::high_res_timer_type"""
  return _spectrum_latency_swig.high_res_timer_now_perfmon()

def high_res_timer_tps():
  """high_res_timer_tps() -> gr::high_res_timer_type"""
  return _spectrum_latency_swig.high_res_timer_tps()

def high_res_timer_epoch():
  """high_res_timer_epoch() -> gr::high_res_timer_type"""
  return _spectrum_latency_swig.high_res_timer_epoch()
class bin_aggregator(object):
    """<+description of block+>"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def make(*args, **kwargs):
        """
        make(unsigned int input_vlen, unsigned int output_vlen, float samp_rate, float fft_size, 
            float center_freq, float bandwidth, float channel_bw, std::vector< unsigned int,std::allocator< unsigned int > > const & output_bin_index) -> bin_aggregator_sptr

        Return a shared_ptr to a new instance of spectrum_latency::bin_aggregator.

        To avoid accidental use of raw pointers, spectrum_latency::bin_aggregator's constructor is in a private implementation class. spectrum_latency::bin_aggregator::make is the public interface for creating new instances.

        Params: (input_vlen, output_vlen, samp_rate, fft_size, center_freq, bandwidth, channel_bw, output_bin_index)
        """
        return _spectrum_latency_swig.bin_aggregator_make(*args, **kwargs)

    make = staticmethod(make)
    def set_bin_index(self, *args, **kwargs):
        """
        set_bin_index(bin_aggregator self, std::vector< unsigned int,std::allocator< unsigned int > > const & output_bin_index)

        Set bin index array.

        Params: (output_bin_index)
        """
        return _spectrum_latency_swig.bin_aggregator_set_bin_index(self, *args, **kwargs)

    def bin_freq(self, *args, **kwargs):
        """
        bin_freq(bin_aggregator self, int i_bin, float center_freq) -> float

        Params: (i_bin, center_freq)
        """
        return _spectrum_latency_swig.bin_aggregator_bin_freq(self, *args, **kwargs)

    __swig_destroy__ = _spectrum_latency_swig.delete_bin_aggregator
    __del__ = lambda self : None;
bin_aggregator_swigregister = _spectrum_latency_swig.bin_aggregator_swigregister
bin_aggregator_swigregister(bin_aggregator)

def bin_aggregator_make(*args, **kwargs):
  """
    bin_aggregator_make(unsigned int input_vlen, unsigned int output_vlen, float samp_rate, float fft_size, 
        float center_freq, float bandwidth, float channel_bw, std::vector< unsigned int,std::allocator< unsigned int > > const & output_bin_index) -> bin_aggregator_sptr

    Return a shared_ptr to a new instance of spectrum_latency::bin_aggregator.

    To avoid accidental use of raw pointers, spectrum_latency::bin_aggregator's constructor is in a private implementation class. spectrum_latency::bin_aggregator::make is the public interface for creating new instances.

    Params: (input_vlen, output_vlen, samp_rate, fft_size, center_freq, bandwidth, channel_bw, output_bin_index)
    """
  return _spectrum_latency_swig.bin_aggregator_make(*args, **kwargs)

class bin_aggregator_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::spectrum_latency::bin_aggregator)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::spectrum_latency::bin_aggregator)> self) -> bin_aggregator_sptr
        __init__(boost::shared_ptr<(gr::spectrum_latency::bin_aggregator)> self, bin_aggregator p) -> bin_aggregator_sptr
        """
        this = _spectrum_latency_swig.new_bin_aggregator_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(bin_aggregator_sptr self) -> bin_aggregator"""
        return _spectrum_latency_swig.bin_aggregator_sptr___deref__(self)

    __swig_destroy__ = _spectrum_latency_swig.delete_bin_aggregator_sptr
    __del__ = lambda self : None;
    def make(self, *args, **kwargs):
        """
        make(bin_aggregator_sptr self, unsigned int input_vlen, unsigned int output_vlen, float samp_rate, float fft_size, 
            float center_freq, float bandwidth, float channel_bw, std::vector< unsigned int,std::allocator< unsigned int > > const & output_bin_index) -> bin_aggregator_sptr

        Return a shared_ptr to a new instance of spectrum_latency::bin_aggregator.

        To avoid accidental use of raw pointers, spectrum_latency::bin_aggregator's constructor is in a private implementation class. spectrum_latency::bin_aggregator::make is the public interface for creating new instances.

        Params: (input_vlen, output_vlen, samp_rate, fft_size, center_freq, bandwidth, channel_bw, output_bin_index)
        """
        return _spectrum_latency_swig.bin_aggregator_sptr_make(self, *args, **kwargs)

    def set_bin_index(self, *args, **kwargs):
        """
        set_bin_index(bin_aggregator_sptr self, std::vector< unsigned int,std::allocator< unsigned int > > const & output_bin_index)

        Set bin index array.

        Params: (output_bin_index)
        """
        return _spectrum_latency_swig.bin_aggregator_sptr_set_bin_index(self, *args, **kwargs)

    def bin_freq(self, *args, **kwargs):
        """
        bin_freq(bin_aggregator_sptr self, int i_bin, float center_freq) -> float

        Params: (i_bin, center_freq)
        """
        return _spectrum_latency_swig.bin_aggregator_sptr_bin_freq(self, *args, **kwargs)

    def history(self):
        """history(bin_aggregator_sptr self) -> unsigned int"""
        return _spectrum_latency_swig.bin_aggregator_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(bin_aggregator_sptr self, int which, int delay)
        declare_sample_delay(bin_aggregator_sptr self, unsigned int delay)
        """
        return _spectrum_latency_swig.bin_aggregator_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(bin_aggregator_sptr self, int which) -> unsigned int"""
        return _spectrum_latency_swig.bin_aggregator_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(bin_aggregator_sptr self) -> int"""
        return _spectrum_latency_swig.bin_aggregator_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(bin_aggregator_sptr self) -> double"""
        return _spectrum_latency_swig.bin_aggregator_sptr_relative_rate(self)

    def start(self):
        """start(bin_aggregator_sptr self) -> bool"""
        return _spectrum_latency_swig.bin_aggregator_sptr_start(self)

    def stop(self):
        """stop(bin_aggregator_sptr self) -> bool"""
        return _spectrum_latency_swig.bin_aggregator_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(bin_aggregator_sptr self, unsigned int which_input) -> uint64_t"""
        return _spectrum_latency_swig.bin_aggregator_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(bin_aggregator_sptr self, unsigned int which_output) -> uint64_t"""
        return _spectrum_latency_swig.bin_aggregator_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(bin_aggregator_sptr self) -> int"""
        return _spectrum_latency_swig.bin_aggregator_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(bin_aggregator_sptr self, int m)"""
        return _spectrum_latency_swig.bin_aggregator_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(bin_aggregator_sptr self)"""
        return _spectrum_latency_swig.bin_aggregator_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(bin_aggregator_sptr self) -> bool"""
        return _spectrum_latency_swig.bin_aggregator_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(bin_aggregator_sptr self, int m)"""
        return _spectrum_latency_swig.bin_aggregator_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(bin_aggregator_sptr self) -> int"""
        return _spectrum_latency_swig.bin_aggregator_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(bin_aggregator_sptr self, int i) -> long"""
        return _spectrum_latency_swig.bin_aggregator_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(bin_aggregator_sptr self, long max_output_buffer)
        set_max_output_buffer(bin_aggregator_sptr self, int port, long max_output_buffer)
        """
        return _spectrum_latency_swig.bin_aggregator_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(bin_aggregator_sptr self, int i) -> long"""
        return _spectrum_latency_swig.bin_aggregator_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(bin_aggregator_sptr self, long min_output_buffer)
        set_min_output_buffer(bin_aggregator_sptr self, int port, long min_output_buffer)
        """
        return _spectrum_latency_swig.bin_aggregator_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(bin_aggregator_sptr self) -> float"""
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(bin_aggregator_sptr self) -> float"""
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(bin_aggregator_sptr self) -> float"""
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(bin_aggregator_sptr self) -> float"""
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(bin_aggregator_sptr self) -> float"""
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(bin_aggregator_sptr self) -> float"""
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(bin_aggregator_sptr self, int which) -> float
        pc_input_buffers_full(bin_aggregator_sptr self) -> pmt_vector_float
        """
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(bin_aggregator_sptr self, int which) -> float
        pc_input_buffers_full_avg(bin_aggregator_sptr self) -> pmt_vector_float
        """
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(bin_aggregator_sptr self, int which) -> float
        pc_input_buffers_full_var(bin_aggregator_sptr self) -> pmt_vector_float
        """
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(bin_aggregator_sptr self, int which) -> float
        pc_output_buffers_full(bin_aggregator_sptr self) -> pmt_vector_float
        """
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(bin_aggregator_sptr self, int which) -> float
        pc_output_buffers_full_avg(bin_aggregator_sptr self) -> pmt_vector_float
        """
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(bin_aggregator_sptr self, int which) -> float
        pc_output_buffers_full_var(bin_aggregator_sptr self) -> pmt_vector_float
        """
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(bin_aggregator_sptr self) -> float"""
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(bin_aggregator_sptr self) -> float"""
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(bin_aggregator_sptr self) -> float"""
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(bin_aggregator_sptr self) -> float"""
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self):
        """pc_throughput_avg(bin_aggregator_sptr self) -> float"""
        return _spectrum_latency_swig.bin_aggregator_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(bin_aggregator_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _spectrum_latency_swig.bin_aggregator_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(bin_aggregator_sptr self)"""
        return _spectrum_latency_swig.bin_aggregator_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(bin_aggregator_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _spectrum_latency_swig.bin_aggregator_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(bin_aggregator_sptr self) -> int"""
        return _spectrum_latency_swig.bin_aggregator_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(bin_aggregator_sptr self) -> int"""
        return _spectrum_latency_swig.bin_aggregator_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(bin_aggregator_sptr self, int priority) -> int"""
        return _spectrum_latency_swig.bin_aggregator_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(bin_aggregator_sptr self) -> std::string"""
        return _spectrum_latency_swig.bin_aggregator_sptr_name(self)

    def symbol_name(self):
        """symbol_name(bin_aggregator_sptr self) -> std::string"""
        return _spectrum_latency_swig.bin_aggregator_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(bin_aggregator_sptr self) -> io_signature_sptr"""
        return _spectrum_latency_swig.bin_aggregator_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(bin_aggregator_sptr self) -> io_signature_sptr"""
        return _spectrum_latency_swig.bin_aggregator_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(bin_aggregator_sptr self) -> long"""
        return _spectrum_latency_swig.bin_aggregator_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(bin_aggregator_sptr self) -> basic_block_sptr"""
        return _spectrum_latency_swig.bin_aggregator_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(bin_aggregator_sptr self, int ninputs, int noutputs) -> bool"""
        return _spectrum_latency_swig.bin_aggregator_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(bin_aggregator_sptr self) -> std::string"""
        return _spectrum_latency_swig.bin_aggregator_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(bin_aggregator_sptr self, std::string name)"""
        return _spectrum_latency_swig.bin_aggregator_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(bin_aggregator_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _spectrum_latency_swig.bin_aggregator_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(bin_aggregator_sptr self) -> swig_int_ptr"""
        return _spectrum_latency_swig.bin_aggregator_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(bin_aggregator_sptr self) -> swig_int_ptr"""
        return _spectrum_latency_swig.bin_aggregator_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(bin_aggregator_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _spectrum_latency_swig.bin_aggregator_sptr_message_subscribers(self, *args, **kwargs)

bin_aggregator_sptr_swigregister = _spectrum_latency_swig.bin_aggregator_sptr_swigregister
bin_aggregator_sptr_swigregister(bin_aggregator_sptr)

bin_aggregator_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
bin_aggregator = bin_aggregator.make;

class bin_statistics(object):
    """<+description of block+>"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make(*args, **kwargs):
        """
        make(unsigned int vlen, unsigned int meas_period) -> bin_statistics_sptr

        Return a shared_ptr to a new instance of spectrum_latency::bin_statistics.

        To avoid accidental use of raw pointers, spectrum_latency::bin_statistics's constructor is in a private implementation class. spectrum_latency::bin_statistics::make is the public interface for creating new instances.

        Params: (vlen, meas_period)
        """
        return _spectrum_latency_swig.bin_statistics_make(*args, **kwargs)

    make = staticmethod(make)
    __swig_destroy__ = _spectrum_latency_swig.delete_bin_statistics
    __del__ = lambda self : None;
bin_statistics_swigregister = _spectrum_latency_swig.bin_statistics_swigregister
bin_statistics_swigregister(bin_statistics)

def bin_statistics_make(*args, **kwargs):
  """
    bin_statistics_make(unsigned int vlen, unsigned int meas_period) -> bin_statistics_sptr

    Return a shared_ptr to a new instance of spectrum_latency::bin_statistics.

    To avoid accidental use of raw pointers, spectrum_latency::bin_statistics's constructor is in a private implementation class. spectrum_latency::bin_statistics::make is the public interface for creating new instances.

    Params: (vlen, meas_period)
    """
  return _spectrum_latency_swig.bin_statistics_make(*args, **kwargs)

class bin_statistics_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::spectrum_latency::bin_statistics)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::spectrum_latency::bin_statistics)> self) -> bin_statistics_sptr
        __init__(boost::shared_ptr<(gr::spectrum_latency::bin_statistics)> self, bin_statistics p) -> bin_statistics_sptr
        """
        this = _spectrum_latency_swig.new_bin_statistics_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(bin_statistics_sptr self) -> bin_statistics"""
        return _spectrum_latency_swig.bin_statistics_sptr___deref__(self)

    __swig_destroy__ = _spectrum_latency_swig.delete_bin_statistics_sptr
    __del__ = lambda self : None;
    def make(self, *args, **kwargs):
        """
        make(bin_statistics_sptr self, unsigned int vlen, unsigned int meas_period) -> bin_statistics_sptr

        Return a shared_ptr to a new instance of spectrum_latency::bin_statistics.

        To avoid accidental use of raw pointers, spectrum_latency::bin_statistics's constructor is in a private implementation class. spectrum_latency::bin_statistics::make is the public interface for creating new instances.

        Params: (vlen, meas_period)
        """
        return _spectrum_latency_swig.bin_statistics_sptr_make(self, *args, **kwargs)

    def history(self):
        """history(bin_statistics_sptr self) -> unsigned int"""
        return _spectrum_latency_swig.bin_statistics_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(bin_statistics_sptr self, int which, int delay)
        declare_sample_delay(bin_statistics_sptr self, unsigned int delay)
        """
        return _spectrum_latency_swig.bin_statistics_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(bin_statistics_sptr self, int which) -> unsigned int"""
        return _spectrum_latency_swig.bin_statistics_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(bin_statistics_sptr self) -> int"""
        return _spectrum_latency_swig.bin_statistics_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(bin_statistics_sptr self) -> double"""
        return _spectrum_latency_swig.bin_statistics_sptr_relative_rate(self)

    def start(self):
        """start(bin_statistics_sptr self) -> bool"""
        return _spectrum_latency_swig.bin_statistics_sptr_start(self)

    def stop(self):
        """stop(bin_statistics_sptr self) -> bool"""
        return _spectrum_latency_swig.bin_statistics_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(bin_statistics_sptr self, unsigned int which_input) -> uint64_t"""
        return _spectrum_latency_swig.bin_statistics_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(bin_statistics_sptr self, unsigned int which_output) -> uint64_t"""
        return _spectrum_latency_swig.bin_statistics_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(bin_statistics_sptr self) -> int"""
        return _spectrum_latency_swig.bin_statistics_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(bin_statistics_sptr self, int m)"""
        return _spectrum_latency_swig.bin_statistics_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(bin_statistics_sptr self)"""
        return _spectrum_latency_swig.bin_statistics_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(bin_statistics_sptr self) -> bool"""
        return _spectrum_latency_swig.bin_statistics_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(bin_statistics_sptr self, int m)"""
        return _spectrum_latency_swig.bin_statistics_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(bin_statistics_sptr self) -> int"""
        return _spectrum_latency_swig.bin_statistics_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(bin_statistics_sptr self, int i) -> long"""
        return _spectrum_latency_swig.bin_statistics_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(bin_statistics_sptr self, long max_output_buffer)
        set_max_output_buffer(bin_statistics_sptr self, int port, long max_output_buffer)
        """
        return _spectrum_latency_swig.bin_statistics_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(bin_statistics_sptr self, int i) -> long"""
        return _spectrum_latency_swig.bin_statistics_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(bin_statistics_sptr self, long min_output_buffer)
        set_min_output_buffer(bin_statistics_sptr self, int port, long min_output_buffer)
        """
        return _spectrum_latency_swig.bin_statistics_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(bin_statistics_sptr self) -> float"""
        return _spectrum_latency_swig.bin_statistics_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(bin_statistics_sptr self) -> float"""
        return _spectrum_latency_swig.bin_statistics_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(bin_statistics_sptr self) -> float"""
        return _spectrum_latency_swig.bin_statistics_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(bin_statistics_sptr self) -> float"""
        return _spectrum_latency_swig.bin_statistics_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(bin_statistics_sptr self) -> float"""
        return _spectrum_latency_swig.bin_statistics_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(bin_statistics_sptr self) -> float"""
        return _spectrum_latency_swig.bin_statistics_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(bin_statistics_sptr self, int which) -> float
        pc_input_buffers_full(bin_statistics_sptr self) -> pmt_vector_float
        """
        return _spectrum_latency_swig.bin_statistics_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(bin_statistics_sptr self, int which) -> float
        pc_input_buffers_full_avg(bin_statistics_sptr self) -> pmt_vector_float
        """
        return _spectrum_latency_swig.bin_statistics_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(bin_statistics_sptr self, int which) -> float
        pc_input_buffers_full_var(bin_statistics_sptr self) -> pmt_vector_float
        """
        return _spectrum_latency_swig.bin_statistics_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(bin_statistics_sptr self, int which) -> float
        pc_output_buffers_full(bin_statistics_sptr self) -> pmt_vector_float
        """
        return _spectrum_latency_swig.bin_statistics_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(bin_statistics_sptr self, int which) -> float
        pc_output_buffers_full_avg(bin_statistics_sptr self) -> pmt_vector_float
        """
        return _spectrum_latency_swig.bin_statistics_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(bin_statistics_sptr self, int which) -> float
        pc_output_buffers_full_var(bin_statistics_sptr self) -> pmt_vector_float
        """
        return _spectrum_latency_swig.bin_statistics_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(bin_statistics_sptr self) -> float"""
        return _spectrum_latency_swig.bin_statistics_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(bin_statistics_sptr self) -> float"""
        return _spectrum_latency_swig.bin_statistics_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(bin_statistics_sptr self) -> float"""
        return _spectrum_latency_swig.bin_statistics_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(bin_statistics_sptr self) -> float"""
        return _spectrum_latency_swig.bin_statistics_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self):
        """pc_throughput_avg(bin_statistics_sptr self) -> float"""
        return _spectrum_latency_swig.bin_statistics_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(bin_statistics_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _spectrum_latency_swig.bin_statistics_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(bin_statistics_sptr self)"""
        return _spectrum_latency_swig.bin_statistics_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(bin_statistics_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _spectrum_latency_swig.bin_statistics_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(bin_statistics_sptr self) -> int"""
        return _spectrum_latency_swig.bin_statistics_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(bin_statistics_sptr self) -> int"""
        return _spectrum_latency_swig.bin_statistics_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(bin_statistics_sptr self, int priority) -> int"""
        return _spectrum_latency_swig.bin_statistics_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(bin_statistics_sptr self) -> std::string"""
        return _spectrum_latency_swig.bin_statistics_sptr_name(self)

    def symbol_name(self):
        """symbol_name(bin_statistics_sptr self) -> std::string"""
        return _spectrum_latency_swig.bin_statistics_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(bin_statistics_sptr self) -> io_signature_sptr"""
        return _spectrum_latency_swig.bin_statistics_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(bin_statistics_sptr self) -> io_signature_sptr"""
        return _spectrum_latency_swig.bin_statistics_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(bin_statistics_sptr self) -> long"""
        return _spectrum_latency_swig.bin_statistics_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(bin_statistics_sptr self) -> basic_block_sptr"""
        return _spectrum_latency_swig.bin_statistics_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(bin_statistics_sptr self, int ninputs, int noutputs) -> bool"""
        return _spectrum_latency_swig.bin_statistics_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(bin_statistics_sptr self) -> std::string"""
        return _spectrum_latency_swig.bin_statistics_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(bin_statistics_sptr self, std::string name)"""
        return _spectrum_latency_swig.bin_statistics_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(bin_statistics_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _spectrum_latency_swig.bin_statistics_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(bin_statistics_sptr self) -> swig_int_ptr"""
        return _spectrum_latency_swig.bin_statistics_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(bin_statistics_sptr self) -> swig_int_ptr"""
        return _spectrum_latency_swig.bin_statistics_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(bin_statistics_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _spectrum_latency_swig.bin_statistics_sptr_message_subscribers(self, *args, **kwargs)

bin_statistics_sptr_swigregister = _spectrum_latency_swig.bin_statistics_sptr_swigregister
bin_statistics_sptr_swigregister(bin_statistics_sptr)

bin_statistics_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
bin_statistics = bin_statistics.make;



